[versions]
# minecraft
mizule = "0.0.1-v197-SNAPSHOT"
minecraft = "1.21"
hangar-publish = "0.1.2"
desertwell = "2.0.4"
mod-publish = "0.5.1"
slf4j = "2.0.13"

[libraries]
desertwell = { group = "net.william278", name = "DesertWell", version.ref = "desertwell" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
hangar-publish = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar-publish" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
mizule-root = { id = "dev.mizule.mizule-build-logic.root", version.ref = "mizule" }
mizule-base = { id = "dev.mizule.mizule-build-logic", version.ref = "mizule" }
mizule-kotlin = { id = "dev.mizule.mizule-build-logic.kotlin", version.ref = "mizule" }
mizule-spotless = { id = "dev.mizule.mizule-build-logic.spotless", version.ref = "mizule" }
mizule-spotless-root = { id = "dev.mizule.mizule-build-logic.spotless.root", version.ref = "mizule" }
mizule-publishing = { id = "dev.mizule.mizule-build-logic.publishing", version.ref = "mizule" }
mizule-blossom = { id = "dev.mizule.mizule-build-logic.blossom", version.ref = "mizule" }
mizule-gremlin = { id = "dev.mizule.mizule-build-logic.gremlin", version.ref = "mizule" }
mizule-platform-paper = { id = "dev.mizule.mizule-build-logic.platform.paper", version.ref = "mizule" }
mizule-aggregate-javadoc = { id = "dev.mizule.mizule-build-logic.aggregate.javadoc", version.ref = "mizule" }
